### ISSUE TITLE
notice some 'unused import' in some files

### ISSUE THREAD

**Issue by s3341458** [merchisdk/sdk#101]
eg 
in sdk/python/draft_comments.py
I saw "import sdk.python.users", I did not see any real usage of this import.
Is there any purpose on that or it is just a purely mistake.

**Comment by DanielCollins** [comment]
the rule is if you remove it and everything still works then it's fine to remove it.

sometimes these things are needed because the module does something in an imperative fashion that needs to be triggered on import (and since definitions are imperatives in python...)
