### ISSUE TITLE
misconfigured eslint in travis ci

### ISSUE THREAD

**Issue by s3341458** [merchisdk/sdk#253]
currently:
./node_modules/eslint/bin/eslint.js 'src/**.ts'

suppose to be:
./node_modules/eslint/bin/eslint.js 'src/*/**.ts'

notice this when I was working on https://github.com/merchisdk/sdk/pull/252

**Comment by DanielCollins** [comment]
why do you have to exclude src in the src folder?

**Comment by s3341458** [comment]
sorry for bad ticket writing, my ticket description is wrong and confused.

so in short, eslint did not check all the ts files inside src/entities folder \o/, I was quite suprised about this as well.

**Comment by DanielCollins** [comment]
i see. eslint seems to defer to https://github.com/isaacs/node-glob

**Comment by DanielCollins** [comment]
./node_modules/eslint/bin/eslint.js 'src/**/*.ts' should also work

**Comment by DanielCollins** [comment]
ah, yes, `./node_modules/eslint/bin/eslint.js 'src/**/*.ts'` is important. 

./node_modules/eslint/bin/eslint.js 'src/*/**.ts' skips files not in a sub directory
