### ISSUE TITLE
design:type will be misleading is null is a optional type

### ISSUE THREAD

**Issue by s3341458** [merchisdk/sdk#275]
https://github.com/merchisdk/sdk/pull/274

is the pr that will demonstrate the problem.

the cause of this problem is due to
![image](https://user-images.githubusercontent.com/2015244/70837754-3b0f4300-1e59-11ea-838c-966b77b17976.png)

suggest to put type defination as property params like arrayType.

I can do this but looking @DanielCollins's opionion properly he would have better idea.

**Comment by DanielCollins** [comment]
https://github.com/merchisdk/sdk/pull/278

**Comment by DanielCollins** [comment]
> properly he would have better idea.

as you've seen typescript has a ticket for it.

we could go and attempt to fix typescript, but it's not just a simple bug, it's a design issue --- they don't have a runtime representation for union types.

so fixing it would presumably involve coming up with a proposal to getting the design changed.

ain't nobody got time for that.

**Comment by DanielCollins** [comment]
now in my PR we have both `type` and `arrayType`.

when i think about it more it would be better to have just `type` and `isArray`, but, i don't care about that enough to want to change it now. well, it's more that i don't have the free time to redo it.

**Comment by s3341458** [comment]
pr is great, but we notice the toFormData still did not properly serialize
relationship optional to null, please address thanks

**Comment by s3341458** [comment]
works all good for now
